### PR TITLE
Update to WildFly 34.0.0.Beta1, GettingStarted requires commons-logging

### LINKED ISSUE #112: GettingStarted 34.0.0.Beta1: "NoClassDefFoundError: org/apache/commons/logging/LogFactory"
This error was reported after updating the archetypes to 34.0.0.Beta1:

```
[INFO] [ERROR] org.wildfly.examples.GettingStartedApplicationIT.testHelloEndpoint -- Time elapsed: 0.105 s <<< ERROR!
[INFO] java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
[INFO]  at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)
[INFO]  at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:91)
[INFO]  at org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:74)
[INFO]  at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:392)
[INFO]  at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:49)
[INFO]  at jakarta.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:86)
[INFO]  at org.wildfly.examples.GettingStartedApplicationIT.testHelloEndpoint(GettingStartedApplicationIT.java:24)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.junit5.ArquillianExtension$1.invoke(ArquillianExtension.java:169)
[INFO]  at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:58)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
[INFO]  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:134)
[INFO]  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:106)
[INFO]  at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
[INFO]  at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:50)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
[INFO]  at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
[INFO]  at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:118)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[INFO]  at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[INFO]  at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[INFO]  at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[INFO]  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[INFO]  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:134)
[INFO]  at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
[INFO]  at org.jboss.arquillian.junit5.ArquillianExtension.interceptInvocation(ArquillianExtension.java:149)
[INFO]  at org.jboss.arquillian.junit5.ArquillianExtension.interceptTestMethod(ArquillianExtension.java:89)
[INFO]  at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[INFO]  at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[INFO] Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
[INFO]  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[INFO]  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[INFO]  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[INFO]  ... 45 more
```

The reason seems to be https://issues.redhat.com/browse/WFLY-19779 - the workaround from https://github.com/wildfly/quickstart/pull/957/ seems to be necessary here, too.

### PR DESCRIPTION
**Pull request by WolfgangHG**
Resolves #112

This is only a draft as long as Wildfly 34 is not released. I send this pull request anyway to point to this issue and get comments on the workaround - as I copied it from the quickstarts, I hope it is valid.

### CODE REVIEW

**Comment by jmesnil** [comment]
@WolfgangHG thanks, you can flag this PR "ready for review" so that the CI jobs will pick it up.
I've added the `hold` label so that it's not merged by accident.

**Comment by WolfgangHG** [comment]
Updated for 34.0 Final and WildFly Controller 26.0.1.Final (supersedes #116 )

Label "hold" could be removed, but I cannot do so.

**Comment by jmesnil** [comment]
@WolfgangHG thanks!
